---
title: "p8105_hw5_ym2715"
author: "Yizhi Ma"
date: "11/8/2018"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

## Problem 1 

```{r load and tidy data, message=FALSE}
file_names = tibble(subject_id = list.files(path = "./data/"))

p1_data_raw = file_names %>% 
	mutate(data = purrr::map(.x = subject_id, ~read_csv(str_c("./data/", .x)))) 

p1_data = p1_data_raw %>% 
  unnest() %>% 
  separate(subject_id, into = c("arm", "subject_id"), sep = "_") %>% 
  separate(subject_id, into = c("subject_id", "suffix")) %>% 
  gather(key = "week", value = "obs_value", week_1:week_8) %>% 
  separate(week, into = c("trash", "week"), sep = "_") %>% 
  mutate(week = as.numeric(week)) %>% 
  select(subject_id, arm_type = arm, week, obs_value) %>% 
  arrange(arm_type, subject_id)
```

```{r spaghetti plot}
p1_data %>% 
  ggplot(aes(x = week, y = obs_value, color = subject_id)) +
  geom_line()+
  facet_grid(~arm_type)+
  labs(
    title = "Observations on subjects over 8 weeks",
    x = "Week",
    y = "Observation values"
  )+
  scale_x_continuous(breaks = c(1:8),
                     labels = c(1:8))+
  theme_bw()+
  theme(legend.position = "bottom")
  
```

## Problem 2

```{r read data, message=FALSE}
homi_raw = read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv")
```

I found that in row 50810, the state value is wrong, where Tulsa should be in OK instead of AL, so I change it.

```{r data wrangling}
homi = homi_raw 
homi[50810, 9] = "OK"
homi$city_state = paste(homi$city, homi$state, sep = ", ")
homi = homi %>% 
  select(-city, -state)
```

```{r some summarise}
total_num = homi %>% 
  group_by(city_state) %>% 
  summarise(total_num = n())

unsolved_num = homi %>% 
  filter(disposition == "Closed without arrest" | disposition == "Open/No arrest") %>% 
  group_by(city_state) %>% 
  summarise(unsolved_num = n())

```

```{r proportion estimate in Baltimore}
balto_total = total_num %>%
  filter(city_state == "Baltimore, MD")

balto_unsolved = unsolved_num %>%
  filter(city_state == "Baltimore, MD")

balto_prop = prop.test(balto_unsolved$unsolved_num, balto_total$total_num)

balto_prop %>% 
  broom::tidy() %>% 
  mutate(city_state = "Baltimore, MD") %>% 
  select(city_state, estimate, conf.low, conf.high) 
  
```

```{r proportion estimate in all cities}

```



